AWSTemplateFormatVersion: "2010-09-09"
Description: Create an ECR repository

Parameters:
  RepositoryName:
    Type: String
    Description: Name of the ECR repository
    Default: my-ecr-repo

Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256

Outputs:
  RepoUri:
    Value: !GetAtt EcrRepository.RepositoryUri
    Description: URI of the created ECR repository
