AWSTemplateFormatVersion: '2010-09-09'
Description: >
  ECS Fargate consumer for AWS IoT -> SQS. FIXED VERSION with AEAD key parameter.

Parameters:
  StackPrefix:
    Type: String
    Default: ecs-iot
  ContainerImage:
    Type: String
    Description: Container image URI for the consumer (ECR/DockerHub). Image must poll SQS and decrypt messages.
  DesiredCount:
    Type: Number
    Default: 1
  AllowedTopic:
    Type: String
    Default: drone/#
    Description: IoT topic filter to subscribe (IoT TopicRule SQL uses this)
  AeadKeyBase64:
    Type: String
    NoEcho: true
    Description: Base64-encoded 32-byte AEAD encryption key for decrypting messages

Resources:

  # -------------------------
  # VPC + Internet Gateway + Subnets + Route
  # -------------------------
  ConsumerVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.100.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${StackPrefix}-vpc"

  ConsumerIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${StackPrefix}-igw"

  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ConsumerVPC
      InternetGatewayId: !Ref ConsumerIGW

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ConsumerVPC
      Tags:
        - Key: Name
          Value: !Sub "${StackPrefix}-public-rt"

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref ConsumerIGW

  # create two subnets across AZs
  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ConsumerVPC
      CidrBlock: 10.100.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: !Sub "${StackPrefix}-subnet-a"

  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ConsumerVPC
      CidrBlock: 10.100.2.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: !Sub "${StackPrefix}-subnet-b"

  # associate route table
  SubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetA
      RouteTableId: !Ref PublicRouteTable

  SubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetB
      RouteTableId: !Ref PublicRouteTable

  # -------------------------
  # Security group for Fargate (allow outbound)
  # -------------------------
  ConsumerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow outbound for consumer
      VpcId: !Ref ConsumerVPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${StackPrefix}-sg"

  # -------------------------
  # SQS queue (IoT -> SQS)
  # -------------------------
  IoTQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${StackPrefix}-iot-queue"

  IoTQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref IoTQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowIoTToSend
            Effect: Allow
            Principal:
              AWS: "*"
            Action: sqs:SendMessage
            Resource: !GetAtt IoTQueue.Arn
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref "AWS::AccountId"

  # -------------------------
  # IAM role IoT assumes to write to SQS (TopicRule)
  # -------------------------
  IoTTopicRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: iot.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: IoTRuleSqsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt IoTQueue.Arn

  # -------------------------
  # IoT Topic Rule that forwards incoming messages to the SQS queue
  # -------------------------
  IoTTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: !Sub "${StackPrefix}_ToSqsRule"
      TopicRulePayload:
        RuleDisabled: false
        Sql: !Sub "SELECT * FROM '${AllowedTopic}'"
        AwsIotSqlVersion: '2016-03-23'
        Actions:
          - Sqs:
              QueueUrl: !Ref IoTQueue
              RoleArn: !GetAtt IoTTopicRuleRole.Arn
        Description: "Forward IoT messages matching AllowedTopic to SQS queue"

  # -------------------------
  # CloudWatch Log Group for ECS container
  # -------------------------
  ConsumerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${StackPrefix}-consumer"
      RetentionInDays: 14

  # -------------------------
  # ECS cluster
  # -------------------------
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${StackPrefix}-cluster"

  # -------------------------
  # IAM roles for ECS
  # -------------------------
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TaskSqsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt IoTQueue.Arn
        # allow logs
        - PolicyName: TaskLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/${StackPrefix}-consumer:*"

  # -------------------------
  # Task definition (Fargate) - FIXED: Added AEAD_KEY_B64
  # -------------------------
  ConsumerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${StackPrefix}-consumer-task"
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: consumer
          Image: !Ref ContainerImage
          Essential: true
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: SQS_QUEUE_URL
              Value: !Ref IoTQueue
            - Name: LOG_GROUP
              Value: !Ref ConsumerLogGroup
            - Name: AEAD_KEY_B64
              Value: !Ref AeadKeyBase64
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ConsumerLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: consumer

  # -------------------------
  # ECS Service
  # -------------------------
  ConsumerService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub "${StackPrefix}-consumer-svc"
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref ConsumerTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ConsumerSecurityGroup
          AssignPublicIp: ENABLED

Outputs:
  ClusterName:
    Description: ECS Cluster name
    Value: !Ref ECSCluster
  ServiceName:
    Description: ECS Service name
    Value: !Ref ConsumerService
  TaskDefinition:
    Description: TaskDefinition family
    Value: !Ref ConsumerTaskDefinition
  SqsQueueUrl:
    Description: URL of the SQS queue IoT writes to
    Value: !Ref IoTQueue
  SqsQueueArn:
    Description: ARN of the SQS queue
    Value: !GetAtt IoTQueue.Arn
  IoTRuleName:
    Description: IoT Topic Rule name
    Value: !Ref IoTTopicRule
  SubnetA:
    Value: !Ref SubnetA
  SubnetB:
    Value: !Ref SubnetB
  VpcId:
    Value: !Ref ConsumerVPC